# Generated by Django 4.0.6 on 2022-07-06 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HE', 'HEADWEAR'), ('APPA', 'APPARELS'), ('TOYS', 'TOYS'), ('PROPS', 'PROPS'), ('OTH', 'OTHERS')], default='OTHERS', max_length=5)),
                ('pub_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('desc', models.TextField(max_length=1024)),
                ('title', models.CharField(max_length=255)),
                ('stock_available', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(verbose_name='date_added')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store_main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_to_img', models.FileField(upload_to='uploads/')),
                ('date_created', models.DateTimeField()),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store_main.item')),
            ],
        ),
    ]
