# Generated by Django 4.0.6 on 2022-07-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(to='store_main.category'),
        ),
    ]
