# Generated by Django 4.0.6 on 2022-07-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_main', '0002_remove_item_category_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path_to_img',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
