# Generated by Django 4.0.6 on 2022-07-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_main', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('HW', 'HEADWEAR'), ('APPA', 'APPARELS'), ('TOYS', 'TOYS'), ('PROPS', 'PROPS'), ('OTH', 'OTHERS')], default='OTH', max_length=5),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
