# Generated by Django 4.0.6 on 2022-07-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_main', '0003_alter_item_category_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('HW', 'HEADWEAR'), ('APPA', 'APPARELS'), ('TOYS', 'TOYS'), ('PROPS', 'PROPS'), ('OTH', 'OTHERS')], default='OTH', max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(to='store_main.category'),
        ),
    ]
