# Generated by Django 4.0.6 on 2022-07-13 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('store_main', '0003_alter_image_path_to_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_qty', models.CharField(default=0, max_length=100)),
                ('saved_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_main.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.yoamiuser')),
            ],
        ),
    ]
