# Generated by Django 4.0.6 on 2022-07-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_main', '0003_alter_image_path_to_img'),
        ('cart', '0002_alter_cartitem_item_qty_alter_cartitem_saved_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='saved_item',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='saved_item',
            field=models.ManyToManyField(null=True, to='store_main.item'),
        ),
    ]
