# Generated by Django 4.0.6 on 2022-07-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_main', '0003_alter_image_path_to_img'),
        ('cart', '0003_remove_cartitem_saved_item_cartitem_saved_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='saved_item',
            field=models.ManyToManyField(to='store_main.item'),
        ),
    ]
