# Generated by Django 4.0.6 on 2022-07-25 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_main', '0003_alter_image_path_to_img'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0004_alter_cartitem_saved_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='saved_item',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='saved_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store_main.item'),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
